image: node:14.15.1

cache:
  key: cache_yarn
  paths:
    - .cache_yarn

stages:
  - install
  - build
  - test
  - deploy

install_functions:
  stage: install
  script:
    - cd ./functions && npm install
  artifacts:
    paths:
      - functions/node_modules

install_client:
  stage: install
  script:
    - cd ./client && yarn install --cache-folder ../.cache_yarn
  artifacts:
    paths:
      - client/node_modules

build_client:
  stage: build
  script:
    - cd ./client && yarn build
  dependencies:
    - install_client
  artifacts:
    paths:
      - client/build

test_client:
  stage: test
  script:
    - cd ./client && yarn test
  dependencies:
    - install_client

test_cypress:
  image: cypress/base:10
  stage: test
  script:
    - cd ./client
    - yarn install
    - yarn runHeadless
  dependencies:
    - install_client

deploy_all_staging:
  stage: deploy
  script:
    - yarn global add firebase-tools --cache-folder ../.cache_yarn
    - firebase deploy --token "$FIREBASE_TOKEN"
  dependencies:
    - install_functions
    - build_client
